# Generated by Django 2.0.7 on 2018-07-18 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submissions',
            name='group_of_submission',
        ),
    ]
