# Generated by Django 2.0.7 on 2018-07-30 20:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hello', '0002_auto_20180730_1536'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='data_type_collection',
            name='admins',
        ),
        migrations.AddField(
            model_name='data_type_collection',
            name='admins',
            field=models.ManyToManyField(related_name='auth_contributors', to=settings.AUTH_USER_MODEL),
        ),
    ]
