# Generated by Django 2.0.7 on 2018-07-19 19:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0002_remove_submissions_group_of_submission'),
    ]

    operations = [
        migrations.AddField(
            model_name='data_type_collection',
            name='last_post',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
