# Generated by Django 2.0.7 on 2018-08-01 16:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hello', '0003_auto_20180730_1541'),
    ]

    operations = [
        migrations.AddField(
            model_name='data_type_collection',
            name='authorized_contributors',
            field=models.ManyToManyField(related_name='auth_contributors', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='data_type_collection',
            name='admins',
            field=models.ManyToManyField(related_name='db_admins', to=settings.AUTH_USER_MODEL),
        ),
    ]
