# Generated by Django 2.0.7 on 2018-07-19 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0003_data_type_collection_last_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data_type_collection',
            name='last_post',
            field=models.DateTimeField(null=True),
        ),
    ]
