# Generated by Django 2.0.7 on 2018-07-19 19:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0004_auto_20180719_1425'),
    ]

    operations = [
        migrations.AddField(
            model_name='submissions',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
