# Generated by Django 2.0.7 on 2018-08-01 16:19

from django.conf import settings
from django.db import migrations, models
import hello.models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0004_auto_20180801_1107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data_type_collection',
            name='authorized_contributors',
            field=models.ManyToManyField(default=hello.models.get_all_users, related_name='auth_contributors', to=settings.AUTH_USER_MODEL),
        ),
    ]
