# Generated by Django 2.0.7 on 2018-07-19 19:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0005_submissions_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='submissions',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
