# Generated by Django 2.0.7 on 2018-08-01 17:03

from django.conf import settings
from django.db import migrations, models
import hello.models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0005_auto_20180801_1119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data_type_collection',
            name='admins',
            field=models.ManyToManyField(default=hello.models.get_admin, related_name='db_admins', to=settings.AUTH_USER_MODEL),
        ),
    ]
