# Generated by Django 2.1 on 2018-08-06 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0006_auto_20180801_1203'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='data_type_collection',
            name='num_tables',
        ),
    ]
