# Generated by Django 2.0.7 on 2018-07-19 20:04

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0006_submissions_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submissions',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2018, 7, 19, 20, 4, 55, 332645, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='submissions',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2018, 7, 19, 20, 4, 55, 332645, tzinfo=utc)),
        ),
    ]
