# Generated by Django 2.1 on 2018-08-06 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0007_remove_data_type_collection_num_tables'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='data_type_collection',
            name='admins',
        ),
        migrations.RemoveField(
            model_name='data_type_collection',
            name='authorized_contributors',
        ),
    ]
