# Generated by Django 2.0.7 on 2018-07-19 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0009_auto_20180719_1505'),
    ]

    operations = [
        migrations.AddField(
            model_name='data_type_collection',
            name='views',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
