# Generated by Django 2.1 on 2018-08-06 18:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0011_data_type_collection_admins'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data_type_collection',
            name='admins',
            field=models.ManyToManyField(related_name='db_admins', to=settings.AUTH_USER_MODEL),
        ),
    ]
