# Generated by Django 2.0.7 on 2018-07-20 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0012_auto_20180719_1519'),
    ]

    operations = [
        migrations.AddField(
            model_name='submissions',
            name='data_name',
            field=models.CharField(default='test', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='submissions',
            name='metadata_name',
            field=models.CharField(default='test', max_length=100),
            preserve_default=False,
        ),
    ]
