# Generated by Django 2.1 on 2018-08-07 06:36

from django.conf import settings
from django.db import migrations, models
import hello.models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0012_auto_20180806_1355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data_type_collection',
            name='admins',
            field=models.ManyToManyField(default=hello.models.get_admin, related_name='db_admins', to=settings.AUTH_USER_MODEL),
        ),
    ]
