# Generated by Django 2.0.7 on 2018-07-20 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0013_auto_20180720_1009'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submissions',
            name='views',
        ),
        migrations.AddField(
            model_name='submissions',
            name='status',
            field=models.CharField(choices=[('s', 'Submitted for Approval'), ('a', 'Accepted'), ('d', 'Denied'), ('m', 'Subject to Modification')], default='s', max_length=1),
        ),
    ]
