# Generated by Django 2.1 on 2018-08-07 06:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0013_auto_20180807_0136'),
    ]

    operations = [
        migrations.RenameField(
            model_name='data_type_collection',
            old_name='admins',
            new_name='authorized_admins',
        ),
    ]
