# Generated by Django 2.1 on 2018-08-10 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0015_auto_20180807_0148'),
    ]

    operations = [
        migrations.AddField(
            model_name='data_type_collection',
            name='public',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='data_type_collection',
            name='status',
            field=models.CharField(choices=[('s', 'Submitted for Approval'), ('a', 'Accepted'), ('d', 'Denied'), ('m', 'Subject to Modification')], default='s', max_length=1),
        ),
    ]
